### ISSUE TITLE
Cannot Import EF into projects - Lacking Proper Documentation

### ISSUE THREAD

**Issue by hankbrigham** [everflow-io/everflow-sdk#6]
After adding the  @everflow/everflow-sdk package to my project, it seems that the contents of the package are not accessible by my project, via es5 and es6 syntax (require and import aren't working). Do I need to have an npmrc config to use this? I'm seeing errors saying that the package may lack proper main configuration in its package.json, which seems to be true as there is no index.js at the top level of the project.

Given that this repo is used and installed differently than a script tag, can you please add some documentation on how to use it and what steps are necessary to make its contents importable?

**Comment by olivierboucher** [comment]
Hi,

I just published version 1.0.7 which should make it easier for you.

```
import { EverflowFingerprintSDK as EF } from '@everflow/everflow-sdk'

console.log(EF);
```

This should work for you now.

**Comment by hankbrigham** [comment]
Thanks for responding so quickly. Unfortunately I still can't import EF from the project even after bumping the package version and using that line of code you shared above. For reference, I'm using NextJS v10.1.3 which has babel and webpack working under the hood.

**Comment by olivierboucher** [comment]
For what it's worth, here is a rollup config for the test project I used to test:

rollup.config.js
```
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import { uglify } from "rollup-plugin-uglify";

export default {
    input: 'index.js',
    output: {
        name: 'EF',
        file: 'dist/everflow-fp-sdk.js',
        format: 'iife'
    },
    plugins: [
        resolve({
            browser: true,
        }),
        commonjs(),
        babel({
            babelrc: false,
            presets: [['@babel/preset-env', { modules: false }]],
            exclude: 'node_modules/**'
        }),
        uglify(),
    ]
}
```

package.json
```
{
  "name": "everflow-sdk-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "rollup -c rollup.config.js"
  },
  "dependencies": {
    "@everflow/everflow-sdk": "^1.0.7"
  },
  "devDependencies": {
    "@babel/core": "7.5.4",
    "@babel/preset-env": "7.5.4",
    "babelrc-rollup": "3.0.0",
    "rollup": "^2.33.3",
    "rollup-plugin-babel": "4.3.3",
    "rollup-plugin-commonjs": "10.0.1",
    "rollup-plugin-node-resolve": "5.2.0",
    "rollup-plugin-uglify": "^6.0.4"
  },
  "author": "",
  "license": "ISC"
}
```

You can try to mimic that using webpack. Unfortunately, we do not offer support for the SDK outside of the standard usage:

```
<script type="text/javascript" 
        src="https://www.YOUR-TRACKING-DOMAIN.com/scripts/sdk/everflow.js"></script>
```
